- name: criando nosso cenario de micro servico
  hosts: docker
  tasks:
   - name: criando o container
     docker_container:
      name: rabbit_jorge
      image: httpd
      state: started
      ports: 
       - 8082:80
      volumes:
       - /index:/usr/local/apache2/htdocs

   - name: download do repositorio
     git:
      repo: http://devops.dexter.com.br/root/docker.git 
      dest: /index/
