- name: remove apache
  hosts: docker
  tasks:
   - name: parar apache
     service:
      name: apache2
      state: stopped
    
   - name: remover apache
     package:
      name: apache2
      state: absent

   - name: instalar nginx
     package:
      name: nginx
      state: present
      update_cache: yes
